title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: M8tth3
github_username: M8tth3
baseurl: "/LabNotebook"
repository: M8tth3/LabNotebook.git
# /student
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true